### ISSUE TITLE
Error with cache on windows

### ISSUE THREAD

**Issue by FeeeeK** [snok/install-poetry#105]
Hello, after restoring the cache of poetry installation on windows, this error occurs:
![image](https://user-images.githubusercontent.com/26704473/199899174-047adea5-1a84-4914-901f-647310b983e8.png)

But poetry definitely exists in that folder:
![image](https://user-images.githubusercontent.com/26704473/199899307-744889bf-1a10-4a48-a1c0-bd98beef1a32.png)

**Comment by JonasKs** [comment]
Is the poetry/Python version the same combination as you’d expect in your cache? 

Feel like we’ve seen this exact thing before, but I may be wrong.

**Comment by JonasKs** [comment]
At, no it probably isn’t, a bit early in the morning and I didn’t read the error properly. 🥱

**Comment by JonasKs** [comment]
Are you allowed to go directly to the `c`-path? Seems like poetry also acknowledges it’s already installed, but how you attempt to access it with a full path isn’t working.

**Comment by FeeeeK** [comment]
This problem is only with windows, everything is normal on other operating systems
![image](https://user-images.githubusercontent.com/26704473/199900032-411e26d8-c2fa-4ce3-9d27-091dd10cbfba.png)

![image](https://user-images.githubusercontent.com/26704473/199899922-a7c546cd-8e93-4fd9-9ed5-bd706fb3ed1c.png)

**Comment by FeeeeK** [comment]
https://github.com/FeeeeK/vkbottle/actions/runs/3391518585

**Comment by sondrelg** [comment]
What happens if you update the cache key (e.g., by appending `-1` to the end of `key`). Does it work the first and second run? 

I suspect this is related to https://github.com/snok/install-poetry/issues/104#issuecomment-1290263880

**Comment by FeeeeK** [comment]
It works at first run, but fails after re-run

https://github.com/FeeeeK/vkbottle/actions/runs/3404825088/jobs/5662355031

![image](https://user-images.githubusercontent.com/26704473/200178390-15801b9d-6a60-44f9-9c67-312acbcb9b9a.png)
![image](https://user-images.githubusercontent.com/26704473/200178411-8edbda73-7965-45fa-be34-33bd3d9019e6.png)

**Comment by sondrelg** [comment]
Gave it a crack, but wasn't successful https://github.com/snok/install-poetry/actions/runs/3405983224

After looking over the readme I see I wrote that "it just doesn't work" a while back ([ref](https://github.com/snok/install-poetry#caching-on-windows-runners)) 😄 so I guess this has never worked - at least not to my knowledge. Weird though.

If anyone wants to take a look at this, PRs are welcome 👍

**Comment by FeeeeK** [comment]
> My build also stopped working on Windows, maybe the same issue? https://github.com/DigiScore/neoscore/actions/runs/3411874104/jobs/5676638880

You need to set the default shell to bash
![image](https://user-images.githubusercontent.com/26704473/201521462-9b05b819-ffc5-496b-8757-2ef852800abd.png)

**Comment by ajyoon** [comment]
@FeeeeK that did the trick, thank you!

**Comment by Hasenpfote** [comment]
If `POERTY_HOME` is specified as anything other than [the default](https://python-poetry.org/docs/#installation), the cache process fails.

Below is an example that worked well for me.

```yaml
name: Caching Poetry on Windows

on: workflow_dispatch

permissions:
  contents: read

jobs:
  create-cache:
    name: caching 1/2 - ${{ matrix.os }}, ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ['3.7', ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: | 
              ~\.local\VERSION
              #~\.local\bin\poetry.exe # Errors occur.
              ~\.local\venv
          key: temp-poetry-${{ matrix.os }}-python-${{ matrix.python-version }}

      - name: Install Poetry for Windows
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1

      - name: Add Poetry to the PATH environment variable
        shell: bash
        run: |
          #echo "${USERPROFILE}\.local\bin" >> $GITHUB_PATH # Errors occur.
          echo "${USERPROFILE}\.local\venv\Scripts" >> $GITHUB_PATH

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: temp-venv-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Foo
        run: |
          poetry run python -V

  # Same as above.
  load-cache:
    needs: create-cache
    name: caching 2/2 - ${{ matrix.os }}, ${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ['3.7', ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: | 
              ~\.local\VERSION
              #~\.local\bin\poetry.exe # Errors occur.
              ~\.local\venv
          key: temp-poetry-${{ matrix.os }}-python-${{ matrix.python-version }}

      - name: Install Poetry for Windows
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1

      - name: Add Poetry to the PATH environment variable
        shell: bash
        run: |
          #echo "${USERPROFILE}\.local\bin" >> $GITHUB_PATH # Errors occur.
          echo "${USERPROFILE}\.local\venv\Scripts" >> $GITHUB_PATH
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: temp-venv-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Foo
        run: |
          poetry run python -V
```

If you remove the commented parts, you will get the following error.
![2022-12-27 00 44 08 github com e8dc679d547d](https://user-images.githubusercontent.com/1502467/209564976-2a4e4463-bd0e-4f1b-b3d7-1d00907ab8b6.png)
