### ISSUE TITLE
Native `setup-python` cache way

### ISSUE THREAD

**Issue by Hongbo-Miao** [snok/install-poetry#108]
`setup-python` supports Poetry cache natively now.
Maybe worth updating the readme! 😃

https://github.com/actions/setup-python#caching-packages-dependencies

**Comment by sondrelg** [comment]
Would you be interested in creating a PR with updated docs @Hongbo-Miao? 🙂

**Comment by Hongbo-Miao** [comment]
Hi @sondrelg my use case is quite simple.

I actually ended with

```yaml
steps:
  - uses: actions/checkout@v3
  - name: Install poetry
    run: pipx install poetry
  - uses: actions/setup-python@v4
    with:
      python-version: '3.9'
      cache: 'poetry'
  - run: poetry install
  - run: poetry run pytest
```

based on the demo here https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
