### ISSUE TITLE
poetry: command not found

### ISSUE THREAD

**Issue by indiVar0508** [snok/install-poetry#109]
After running poetry setup action, poetry is not getting accessed, and gives error `poetry: command not found` even for the action job also if you see the logs below.
can you help me on how to access poetry for installing depdencies, i followed the documentation for one of my [job](https://github.com/corridor/sqlalchemy-history/actions/runs/3592706774/jobs/6048741773#step:5:39) but it is failing, can you help me resolve the issue

```
Setting Poetry installation path as /home/runner/.local/

Installing Poetry 👷

Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/runner/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.2.2)
Installing Poetry (1.2.2): Creating environment
Installing Poetry (1.2.2): Installing Poetry
Installing Poetry (1.2.2): Creating script
Installing Poetry (1.2.2): Done

Poetry (1.2.2) is installed now. Great!

You can test that everything is set up by executing:

`poetry --version`

/home/runner/work/_actions/snok/install-poetry/v1.3.1/main.sh: line [33](https://github.com/corridor/sqlalchemy-history/actions/runs/3592706774/jobs/6048741773#step:5:35): poetry: command not found
/home/runner/work/_actions/snok/install-poetry/v1.3.1/main.sh: line [34](https://github.com/corridor/sqlalchemy-history/actions/runs/3592706774/jobs/6048741773#step:5:36): poetry: command not found
/home/runner/work/_actions/snok/install-poetry/v1.3.1/main.sh: line [35](https://github.com/corridor/sqlalchemy-history/actions/runs/3592706774/jobs/6048741773#step:5:37): poetry: command not found
/home/runner/work/_actions/snok/install-poetry/v1.3.1/main.sh: line [37](https://github.com/corridor/sqlalchemy-history/actions/runs/3592706774/jobs/6048741773#step:5:39): poetry: command not found

Installation completed. Configuring settings 🛠

Done ✅

If you are creating a venv in your project, you can activate it by running 'source .venv/bin/activate'. If you're running this in an OS matrix, you can use 'source $VENV' instead, as an OS agnostic option
```

**Comment by PhilippWillms** [comment]
Maybe your issue is related to my one:

The matrix testing has worked fine so far, but now I want to verify the correctly installed packages (specified in toml file) by executing a command (cf. last line in the snippet below). 

```
jobs:
  test-run:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
      - name: Install poetry in virtual environment
        uses: snok/install-poetry@v1.3.3
        with:
          version: 1.4.0
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true
      - name: Install dependencies and execute minimum example
        run: |
          poetry install --no-interaction
          rllib train file tests/mwe_cartpole_ppo.yml
```
But the job quites with the following statement.
> /home/runner/work/_temp/eaaed385-33c0-4b52-877f-1b9e95578378.sh: line 2: rllib: command not found
> Error: Process completed with exit code 127.

I wonder why this is happening as it is working in another project with subsequent poetry-based commands, e.g.
_poetry run pytest tests/_
