### ISSUE TITLE
Skip poetry install step with cache hit

### ISSUE THREAD

**Issue by MarvinXu** [snok/install-poetry#111]
![image](https://user-images.githubusercontent.com/7382357/206207203-5bbf9df9-0e26-4a25-a32e-0d95c5aeaa10.png)

As you can see, poetry cache works, but it still takes 3s to "Install Poetry". Is it possible to skip this step when cache hit, just like "Install dependencies"?

**Comment by sondrelg** [comment]
Yes, sure that would be great! :clap:

**Comment by MarvinXu** [comment]
There is one problem though, if you skip poetry install, the passed-in poetry config will not be set.

I manually cached `.venv` directory in my project, so after I updated my denpendencies, there was an error resaving venv cache because the default venv path is `{cache-dir}/virtualenvs`:
> Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.

I fixed it by manually run `poetry config`:
```yml
#----------------------------------------------
#  -----  install & configure poetry  -----
#----------------------------------------------
- name: Load cached Poetry installation
  id: cached-poetry
  uses: actions/cache@v3
  with:
    path: ~/.local  # the path depends on the OS
    key: poetry-0  # increment to reset cache
- name: Install Poetry
  if: steps.cached-poetry.outputs.cache-hit != 'true'
  uses: snok/install-poetry@v1
- run: |
    poetry config virtualenvs.in-project true
#----------------------------------------------
#       load cached venv if cache exists
#----------------------------------------------
- name: Load cached venv
  id: cached-poetry-dependencies
  uses: actions/cache@v3
  with:
    path: .venv
    key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
#----------------------------------------------
# install dependencies if cache does not exist
#----------------------------------------------
- name: Install dependencies
  if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
  run: poetry install --no-interaction --no-root
#----------------------------------------------
#              run scripts
#----------------------------------------------
- name: Run scripts
  run: |
    poetry run start
```
