### ISSUE TITLE
Add env: section to parse envs that are used in each poetry call

### ISSUE THREAD

**Issue by fxmb** [snok/install-poetry#116]
This is not really an issue but I would like to have a field `env:` where I can pass in env variables that are available in the virtualenv whenever e.g. `poetry run` is called. Is this possible somehow? I can obv add these commands every via `export XY=abc && poetry run...` but this is not concise and easily leads to errors....

**Comment by sondrelg** [comment]
You can set environment variables in your workflow, like this:

```yaml
name: Test

on:
    push 

env:
  PYTHON_VERSION: "3.10.5"
  POETRY_VERSION: 1.2.2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # run tests here
```

Would that be enough, or is there a reason that wouldn't work for you?
