### ISSUE TITLE
urllib.error.URLError: <urlopen error unknown url type: https>

### ISSUE THREAD

**Issue by brylie-wolt** [snok/install-poetry#121]
When running the install poetry action with Python 3.11, I am getting the following error:

> File "/opt/actions-runner/_work/_tool/Python/3.11.3/x64/lib/python3.11/urllib/request.py", line 1419, in unknown_open
>    raise URLError('unknown url type: %s' % type)
> urllib.error.URLError: <urlopen error unknown url type: https>

The configured steps are:

```yaml
steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
            virtualenvs-create: true
            virtualenvs-in-project: true
            installer-parallel: true
```
