### ISSUE TITLE
The `with` `virtualenvs-in-project` setting does not seem to work for me

### ISSUE THREAD

**Issue by HarrisonWilde** [snok/install-poetry#124]
My action looks like this:

```
name: Build MkDocs

on: 
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}
      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root --with docs
      - name: Install project
        run: poetry install --no-interaction --with docs
      - name: Deploy MkDocs
        run: |
          source .venv/bin/activate
          mkdocs gh-deploy --force --clean --verbose
```

I used to instead use the `with` usage underneath the action, but I kept getting an error that on the "Install Dependencies" stage of the workflow it was looking for a virtual env outside of the project folder. Is this a problem with caching the install?
