### ISSUE TITLE
Cache not found

### ISSUE THREAD

**Issue by jessicabowden** [snok/install-poetry#126]
Caching the poetry install works fine but seem to be having issues with caching the virtualenv, see:

<img width="1065" alt="Screenshot 2023-07-05 at 12 39 54 PM" src="https://github.com/snok/install-poetry/assets/9529094/0c75cd6c-df08-4a66-8c13-120e0e985ee9">

Here is the workflow definition:
```
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'
      
      - name: Install and configure poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
      
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local  # the path depends on the OS
          key: poetry-0  # increment to reset cache

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      
      - name: Lint
        run: |
          poetry run ruff . --format github
          poetry run black --skip-string-normalization .
          poetry run isort .
```
