### ISSUE TITLE
Does not respect POETRY_HOME

### ISSUE THREAD

**Issue by mahmoudhossam** [snok/install-poetry#127]
I'm trying to install poetry in an alternative location as per [the documentation](https://python-poetry.org/docs/#ci-recommendations)

The problem with this action is that even when `POETRY_HOME` is set, it still installs to the default location.

Example minimal workflow:

```yaml
name: Test Install Poetry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POETRY_HOME: /usr
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
```

Example run: https://github.com/mahmoudhossam/test-poetry/actions/runs/5552599337/jobs/10140141699
