### ISSUE TITLE
$VENV not set on Poetry installation cache restore

### ISSUE THREAD

**Issue by emanueljg** [snok/install-poetry#138]
When restoring a Poetry installation from cache, it doesn't seem $VENV gets set.

Steps to reproduce:
1. Implement https://github.com/snok/install-poetry#caching-the-poetry-installation
2. use `source $VENV` in a later step
3. flow fails due to unset var

...which I guess makes sense since it's the action that sets $VENV, and since the action won't run on a cache hit, the var remains unset. This deserves a mention in the documentation.

**Comment by sondrelg** [comment]
Yeah this is reasonable. Would you like to contribute a doc update? 🙂

**Comment by emanueljg** [comment]
> Yeah this is reasonable. Would you like to contribute a doc update? 🙂

Sure! But now that I think about it - couldn't we deprecate the use of $VENV altogether? 
- Some examples in the documentation doesn't use $VENV, some do
- Without reading the docs, it's not clear where it comes from. Newcomers to Poetry might think it's set by Poetry itself (hell, I was). A lot of GH Actions are just shared by copy-paste and as such the origin of $VENV might be lost in translation
- As seen here, it breaks on cache hit.

Why not just tell the user to add this to their matrix  instead? 
```yml
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - VENV: .venv/bin/activate
          - os: windows-latest
            VENV: .venv/scripts/activate
```
(https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations)
- the steps are not bloated with something as trivial as a conditional env setting, and it's easily signaled that the var depends on the OS.
- the user is fully aware of what is going on
- doesn't break on a cache hit

It potentially breaks on a more exotic matrix configuration (i.e. a windows runner not identified by `windows-latest`) but that's easily spotted by the user.
