### ISSUE TITLE
The cached poetry installation doesn't recover settings like `virtualenvs-in-project` so caching venvs breaks

### ISSUE THREAD

**Issue by sebastian-correa** [snok/install-poetry#150]
Hi! I'm using this action to install poetry like this:

```YAML
name: Syle check

on: push

jobs:
  style-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-0-${{ runner.os }}

      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv if it exists
        id: venv-cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-${{ github.workflow }}

      - name: Install dependencies
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --only dev

      - name: Lint codebase
        run: poetry run ruff check

      - name: Format codebase
        run: poetry run ruff format
```

As you can see, I'm caching both the poetry install and the venv creation. However, any runs after the one that creates the cache entry for the poetry install don't correctly set `virtualenvs-in-project`, so if I change my lock file, the venv install step fails to cache (because its using a cached poetry installation that hasn't been configured to install the venv in `.venv` and installs it to the default location).

How can this be fixed? For now it seems I have to disable the caching of installing poetry, or add a new intermediate step that runs the correct `poetry config` steps. Maybe we also need to cache the output of `poetry config --list --local`?
