### ISSUE TITLE
Add support for installation of poetry 2.x

### ISSUE THREAD

**Issue by moattarwork** [snok/install-poetry#164]
Currently, the issue can be resolved by referring to the hashcode of the 2.0.1 as 
```
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          installation-arguments: --git https://github.com/python-poetry/poetry.git@bd500dd3bdfaec3de6894144c9cedb3a9358be84
```
However I think it requires a more sustainable solution possible using pipx
