### ISSUE TITLE
Installation fails on arm

### ISSUE THREAD

**Issue by YuviGold** [snok/install-poetry#165]
Github's published a new [hosted runner](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/) for arm architecture. But poetry installation is failing due to permission error. 

<details>
 <summary>Simple GHA code</summary>

```yaml
name: test poetry installation

on:
  pull_request:


jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-22.04-arm, ubuntu-24.04.arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: false
```

</details>

<details>
<summary>ubuntu-latest</summary>

```
Setting Poetry installation path as /home/runner/.local

Installing Poetry 👷

Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/runner/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.8.5)
Installing Poetry (1.8.5): Creating environment
Installing Poetry (1.8.5): Installing Poetry
Installing Poetry (1.8.5): Creating script
Installing Poetry (1.8.5): Done

Poetry (1.8.5) is installed now. Great!

You can test that everything is set up by executing:

`poetry --version`


Installation completed. Configuring settings 🛠

Done ✅
```

</details>

<details>
 <summary>ubuntu-22.04-arm logs</summary>

```
Setting Poetry installation path as /home/runner/.local

Installing Poetry 👷

Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/runner/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.8.3)
Installing Poetry (1.8.3): Creating environment
Installing Poetry (1.8.3): Installing Poetry
Installing Poetry (1.8.3): Creating script
Installing Poetry (1.8.3): Done

Poetry (1.8.3) is installed now. Great!

To get started you need Poetry's bin directory (/home/runner/.local/bin) in your `PATH`
environment variable.

Add `export PATH="/home/runner/.local/bin:$PATH"` to your shell configuration file.

Alternatively, you can call Poetry explicitly with `/home/runner/.local/bin/poetry`.

You can test that everything is set up by executing:

`poetry --version`


[Errno 13] Permission denied: '/home/runneradmin/.config/pypoetry/config.toml'
```

</details>
