### ISSUE TITLE
Basic Example. Bad interpreter: No such file or directory.

### ISSUE THREAD

**Issue by ChristianMichelsen** [snok/install-poetry#17]
Hi snok!

I have with succes used your template earlier, but now I run into trouble. Due to trouble finding the bug, I went back to your basic script, only to find that this also caused a problem. I am very new to Github Actions, so it might just be me who is missing something vert basic. I have taken you basic example and changed a few things; that it should run on push (for testing), use Python 3.8, and not run coverage, i.e. the following:

```
name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/
```

When I push my files to Github, the action fails in the "Run tests" step with the following error:

![Screenshot 2021-01-21 at 11 59 59](https://user-images.githubusercontent.com/38658417/105342121-3ed6d280-5be0-11eb-8855-c3b73139d58b.png)

Do you have any tips or tricks for fixing this?

**Comment by sondrelg** [comment]
Strange 🤔  

Is this from a public repo? If so, would you link the run itself?

If not, could you also include the output from the `install poetry` step?

------

I'll see if I can replicate the error after work 👍

**Comment by sondrelg** [comment]
Have you tried invalidating the cache btw? You might just need to update your `key` to `*-2` or whatever to invalidate the existing cache and rebuild your venv.

**Comment by ChristianMichelsen** [comment]
The run itself kan be seen [here](https://github.com/ChristianMichelsen/metadamage/runs/1741211890?check_suite_focus=true) or here as an image:

![Screenshot 2021-01-21 at 13 27 30](https://user-images.githubusercontent.com/38658417/105351227-911df080-5bec-11eb-827f-ea6162ebd060.png)


Regarding you second suggestion, do you just mean changing `key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}` to `key: *-2` or?

**Comment by JonasKs** [comment]
Yes, you can see an example [here](https://github.com/snok/django-guid/blob/master/.github/workflows/test.yml#L61).

**Comment by sondrelg** [comment]
You could also test like this to verify

```
name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/
```

I.e., by removing the cache step. 

I'm not sure this is why you're having problems, but as you can see in your original run, the `Install dependencies` isn't running. Your job is re-using the venv it cached in another run.
