### ISSUE TITLE
Rethink recommendation about conditionally running `poetry install`

### ISSUE THREAD

**Issue by amotl** [snok/install-poetry#19]
Dear Sondre,

thanks for conceiving and maintaining this excellent package. Apart from #18, we have been able to ramp it up quickly by following the recommendations within the documentation, which are great.

However, there is one specific detail I would like to solicit attention for.

Your suggestion to only run `poetry install` conditionally like
```yaml
- name: Install dependencies
  if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
  run: poetry install
```

might fall short because `poetry install` without other options is responsible for installing the root package **and** its dependencies. However, we only want to cache the dependencies here, right? Otherwise, the CI job will probably not test the current code being brought in through the very patch coming from the PR.

So, if you don't have any objections on this detail, I would like to suggest to instead use a procedure like
```yaml
- name: Install dependencies
  if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
  run: poetry install --no-interaction --no-root

- name: Install library
  run: poetry install --no-interaction
```

The key is the `--no-root` option here which is bound to the conditional step only invoked when running on a cold cache.

Please change my mind if you believe I am wrong on this.

With kind regards,
Andreas.
