### ISSUE TITLE
Action versioning not following GitHub recommendations

### ISSUE THREAD

**Issue by frank-fischer-by** [snok/install-poetry#41]
GitHub Actions has [_recommendations_ on how to handle releases via tagging](https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management):

> * Create a release using semantic versioning. For more information, see "Creating releases."
> * Move the major version tag (such as v1, v2) to point to the Git ref of the **current** release. [...]

It would be great if this repository adapts the suggested recommendations 🙂.

That way every user could simply do

```yaml
uses: snok/install-poetry@v1
```

in their GitHub action and will always get the latest 1.X.Y version.

**Comment by sondrelg** [comment]
Can you not do this today?

```
uses: snok/install-poetry@v1
```

If so, am I reading this correctly - that we would just need to `git tag` each new release with v1 to move the v1 reference? 

I would love to do this, as it would save us having to update patch versions in the readme every time we update something haha 🙂  Do you think this would be something we could automate with a workflow triggered by a release in the repo?

**Comment by sondrelg** [comment]
Seems like a nice way to handle it 👏 

Perhaps we don't even need a separate action - [this](https://github.com/pre-commit/mirrors-mypy/blob/master/.github/workflows/main.yml#L20) seems to have ~all the code we need. 

Would you be interested in trying to implement it? If not I'll try to get this done within a day or two 👍

**Comment by sondrelg** [comment]
You'll need to help me out here @frank-fischer-by @JonasKs; how does this look? 🙂 

https://github.com/snok/install-poetry/blob/main/.github/workflows/tag_release.yml

**Comment by JonasKs** [comment]
Looks good to me, but I guess that action don't really scale if you need a `v2`.   
Maybe check `github.event.ref` and get the first two letters, and release to that version? So if a `v2.2` is pushed, it push to `v2` and not `v1`?

**Comment by miigotu** [comment]
> Looks good to me, but I guess that action don't really scale if you need a `v2`.
> Maybe check `github.event.ref` and get the first two letters, and release to that version? So if a `v2.2` is published, push to `v2` and not `v1`?

v2 ends up being the highest versioned of v2, so if you have a v2.3.4 and a v2.4, v2.4 is pointed to by v2 tag, as well as the v2.2 tag. v2.3.4 would still be tagged as v2.3.4 and v2.3

**Comment by sondrelg** [comment]
Yep I think this sounds like the desired behaviour. In other words, someone who has specified

```
- name: Install Poetry
  uses: snok/install-poetry@v2
```

will always be on the latest version of v2 👍

**Comment by frank-fischer-by** [comment]
Sorry, currently have a lot on my plate, so I simply didn't get around to creating the PR.
The functionality generally looks great. I just ran a workflow and tested that 

```yaml
- name: Install Poetry
  uses: snok/install-poetry@v1
```
correctly pulls `1.1.6` ❤️ 

As @JonasKs pointed out, that code is not 100% future proof, once `v2` would roll around, so maybe add

```yaml
run: |
  git tag "${GITHUB_REF:0:2}"
  git push origin HEAD:refs/heads/master --tags --force
```

Concerning the discussion around (other) tags, that's not really defined by GitHub.

As long as `v1`points to "latest" `v1.X.Y`that's probably the 99.9% case.
Having `v1.X` might be "nice" but I personally wouldn't bother if semantic versioning is used.

**Comment by sondrelg** [comment]
I suppose we could tag major _and_ minor versions if we wanted 🤔

**Comment by sondrelg** [comment]
Quickly tested in a separate repo: https://github.com/sondrelg/test-tagging/runs/3069653365?check_suite_focus=true

I believe this workflow should do the trick
```yaml
name: Tag releases with minor and major version

on:
  release:
    types: [published]

jobs:
  tag-v1:
    name: Tag v1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update tag
        run: |
          major_tag="$(python get_version.py "${GITHUB_REF}" major)"
          minor_tag="$(python get_version.py "${GITHUB_REF}" minor)"
          git tag $major_tag
          git tag $minor_tag
          git push origin HEAD:refs/heads/master --tags --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Where `get_version.py` can be kept in the repo and looks like this

```python
import sys

from packaging import version

if __name__ == '__main__':
    ref = sys.argv[1]  # ref will usually look like refs/tags/v1.0.1
    major = sys.argv[2] == 'major'
    version = version.parse(ref.split('refs/tags/v')[1])

    if major:
        print(f'v{version.major}')
    else:
        print(f'v{version.major}.{version.minor}')
```

Does that seem like a reasonable solution?
