### ISSUE TITLE
How can we speed up this workflow?

### ISSUE THREAD

**Issue by peterbe** [snok/install-poetry#43]
We use something like this:

```
      - name: Install Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.8"

      - name: Install Python poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2.1.6
        with:
          path: yari/deployer/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/pr-review-companion.yml') }}

      - name: Install poetry dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          cd yari/deployer
          poetry install --no-interaction --no-root
```

It works great! I'm really happy about the workflow and it's been solid. 

There's just one problem, the...

```
      - name: Install Python poetry
        uses: snok/install-poetry@v1.1.6
```

...lines are usually the slowest part of our whole workflow. 
[For example](https://github.com/mdn/content/runs/3165067066?check_suite_focus=true):

<img width="1093" alt="Screen Shot 2021-07-26 at 3 59 36 PM" src="https://user-images.githubusercontent.com/26739/127051098-085845cf-7e21-495f-a5b7-1d9f3b6826ff.png">

This is a very typical thing. The slowest one is "Install Python poetry". It's roughly 10-15 seconds. 

We use Python (and poetry) as part of our build process for [our CMS](https://github.com/mdn/yari). First, there's some Node code that builds the raw content into rendered HTML. Then a Python script runs some analysis on that built HTML and it uploads the built files to AWS S3. 

So we run this workflow a LOT. For every single build of our content, which is authored through GitHub.
See https://github.com/mdn/content/actions/workflows/pr-review-companion.yml

Is there a way we can use caching or something to speed up this workflow?

**Comment by peterbe** [comment]
Instead of looking for milliseconds within the script, perhaps the best bet is to cache the whole `virtualenvs` folder. Something similar to how we're doing with the actual `.venv` which we later use `poetry` for creating.

**Comment by miigotu** [comment]
Also cache `$(pip cache dir)` that way poetry and dependencies are cached and don't need to be downloaded.

**Comment by peterbe** [comment]
> Also cache `$(pip cache dir)` between installing python and installing poetry. That way poetry and dependencies are cached and don't need to be downloaded. Also, move your venv cache to before poetry install.
> 
> So:
> Install python
> Restore cached pip cache
> Restore cached venv
> Install poetry.
> Install dependencies

Sorry, how would that help `snok/install-poetry@v1.1.6`? 
Does `snok/install-poetry` depend on `pip` (and its `pip cache dir`)?

I wasn't sure it there was something I missed so I tried it. Put in:

```
     - name: Cache pip
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/pr-deployer.yml') }}
```
which I can see, clearly restores the pip cache (`~/.cache/pip` is the same as `$(pip cache dir)`). 
But `snok/install-poetry@v1.1.6` still takes the same old time.

**Comment by peterbe** [comment]
Perhaps you mean because `get-poetry.py` internally runs `python -m pip install virtualenv -t $tmpdir` which could use `pip cache dir`. 
But either it's not working or it's not making any difference.

**Comment by miigotu** [comment]
> > Also cache `$(pip cache dir)` between installing python and installing poetry. That way poetry and dependencies are cached and don't need to be downloaded. Also, move your venv cache to before poetry install.
> > 
> > So:
> > Install python
> > Restore cached pip cache
> > Restore cached venv
> > Install poetry.
> > Install dependencies
> 
> Sorry, how would that help `snok/install-poetry@v1.1.6`? 
> Does `snok/install-poetry` depend on `pip` (and its `pip cache dir`)?
> 
> I wasn't sure it there was something I missed so I tried it. Put in:
> 
> ```
>      - name: Cache pip
>         uses: actions/cache@v2.1.6
>         with:
>           path: ~/.cache/pip
>           key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/pr-deployer.yml') }}
> ```
> which I can see, clearly restores the pip cache (`~/.cache/pip` is the same as `$(pip cache dir)`). 
> But `snok/install-poetry@v1.1.6` still takes the same old time. 
> 

You have to let it cache it once, then the next time it will restore the cache it will be faster. Also, the ordering matters.

**Comment by miigotu** [comment]
> Perhaps you mean because `get-poetry.py` internally runs `python -m pip install virtualenv -t $tmpdir` which could use `pip cache dir`. 
> But either it's not working or it's not making any difference. 

It also does pip install inside the venv.

**Comment by sondrelg** [comment]
I guess there's a few things we could do:

1. We could try to cache the scripts we fetch
2. We could configure our workflows to run the `install-poetry` script faster, and
3. Could we somehow cache the entire installation?

To your point @peterbe I don't think point 1 is worth spending time on. I tried running a fresh install with the `install-poetry` script on my laptop and that took 12 seconds, so that's probably 99% of the action's runtime in most cases 🙂 

I would imagine that caching all pip downloads would help a lot - it certainly seems like a good option is you're already caching your venv, but I wouldn't be surprised if the script itself is a bit slow.

Would caching the entire installation directory work? I would imagine this would be the fastest thing we could do.

**Comment by peterbe** [comment]
> You have to let it cache it once, then the next time it will restore the cache it will be faster.

No, I tested that. I made sure that there was a commit such that the cache **retrieval** did work. 

I think the fastest way to make something is to *avoid* the work. 
Downloads from npmjs.com or pypi.org are usually very fast. Having the tarballs locally doesn't actually make a huge difference. What makes a HUGE difference is if you can cache the entire `node_modules` or `.venv` directories whole.

**Comment by peterbe** [comment]
> Would caching the entire installation directory work? I would imagine this would be the fastest thing we could do.

It certainly would. But isn't there some important environment variable set'ing that needs to happen too. 
I actually have never understood how `install-python.py` works but it's not inconceivable that it does 2 things: creating a directory, and setting an env var (or something related to `$path`).

**Comment by sondrelg** [comment]
I think all the script does in this context, is install the correct packages. The action needs to set the path variable, since `PATH` in Github actions works a little bit differently. See [this](https://github.com/snok/install-poetry/blob/main/scripts/v1.2/main.sh#L44) line 🙂 

If caching the installation directory works, we probably wouldn't need to make any additional changes to the action itself to make this work as intended, since the installation script exits early if it Poetry is already installed. The installation directory will be `$HOME/.local/` on an ubuntu runner if you want to test if that works @peterbe 🙂 
 
If it works and #40 is merged, I guess we could also very easily go one step further and try to detect whether the `$POETRY_HOME`  installation directory already exists or not before fetching script to shave off another few ms 🙂

**Comment by peterbe** [comment]
It worked!! 

<img width="1171" alt="Screen Shot 2021-07-27 at 9 48 38 AM" src="https://user-images.githubusercontent.com/26739/127165396-66766ca3-4761-4807-aeaa-be8f2d780d14.png">

You can see it in action here: https://github.com/mdn/yari/runs/3172270869

The magic was to add this:

```yml
      - name: Load cached .local
        uses: actions/cache@v2.1.6
        with:
          path: ~/.local
          key: dotlocal-${{ runner.os }}-${{ hashFiles('.github/workflows/pr-deployer.yml') }}
```

**Comment by peterbe** [comment]
I'm so please with the result (and for the benefit of my own notes/memory), that I blogged about it: https://www.peterbe.com/plog/install-python-poetry-github-actions-faster
Hopefully this helps others that might stumble into this issue. 

Wanna close it for now @sondrelg ?

**Comment by sondrelg** [comment]
That's awesome @peterbe! I'll see if I can add this to the main readme so that other users can benefit as well 🚀 I might close this following that if you don't mind 🙂 Thanks for raising this and doing all the testing!

On a related note, I think Github Actions are releasing support for running actions within actions more or less as we speak ([this](https://github.com/actions/runner/commit/5281434f3f9005c11a366409b24d9470b166fdfe) was merged today) - perhaps this is also something we could build into the action itself at some point when that's possible 🎉

**Comment by peterbe** [comment]
The future is bright!

**Comment by miigotu** [comment]
Question, is caching poetry's cache included in the readme? Sorry I dont have time to look:

```yaml
    - name: Restore poetry cache
      if: success() && !env.ACT
      uses: actions/cache@v2
      with:
        path: $(poetry config cache-dir)
        key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
```
