### ISSUE TITLE
Add support to install poetry plugins

### ISSUE THREAD

**Issue by pbk0** [snok/install-poetry#53]
Poetry 1.2+ will now support plugins. It will be a good idea to support installing plugins if the poetry version is 1.2+.
That is by adding the below lines to the `main.sh` script:
```bat
<...>
plugins=$7
<...>
poetry plugin add $plugins
<...>
```

**Comment by sondrelg** [comment]
Thanks for bringing this up @pbk0 👏 

I just have a few questions, in case you already know:

- What happens when you run `poetry plugin add <plugin>`? Does it make changes to the lockfile or does it start a process separate from the normal `poetry install`? 
- How can I test plugin installation locally? I tried this, without luck:

```
❯ poetry self update --preview            
Updating Poetry to 1.2.0a2

Updating dependencies
Resolving dependencies... (4.3s)

Package operations: 0 installs, 1 update, 0 removals

  - Updating charset-normalizer (2.0.5 -> 2.0.6)

Updating the poetry script

Poetry (1.2.0a2) is installed now. Great!

❯ poetry plugin add poetry-version-plugin
The command "plugin" is not defined.
```

**Comment by pbk0** [comment]
Can you make sure if you have multiple poetry installations? (try `which/where poetry`) 
Also, I am assuming the poetry installation is isolated. I faced some issues with stale poetry installations. So maybe clean things up and try `1.2.0a2`
Below script might be useful

```bat
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py > get-poetry.py
python get-poetry.py --uninstall
rm get-poetry.py

curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py > install-poetry.py
python install-poetry.py --uninstall
python install-poetry.py --version 1.2.0a2
rm install-poetry.py

poetry --version
```

**Comment by sondrelg** [comment]
I think you were right about dual installations, got it to work now 👍 

So the solution would just be something like specifying:

```yaml
- name: Install and configure Poetry
  uses: snok/install-poetry@v1
  with:
    version: 1.2.0a2
    plugins: |
        poetry-plugin-a
       poetry-plugin-b
```

or 

```yaml
- name: Install and configure Poetry
  uses: snok/install-poetry@v1
  with:
    version: 1.2.0a2
    plugins: poetry-plugin-a, poetry-plugin-b
```

or 

```yaml
- name: Install and configure Poetry
  uses: snok/install-poetry@v1
  with:
    version: 1.2.0a2
    plugins: poetry-plugin-a poetry-plugin-b
```

Where the `plugins` inputs should be parsed as a list, and installed in `main.sh` by running `poetry plugin add {parsed list}`?

That sounds doable 👍 

Would you be interested in creating a PR for this @pbk0?
