### ISSUE TITLE
Unable to use '~' in virtualenvs-path from v1.2.0

### ISSUE THREAD

**Issue by JaimeLennox** [snok/install-poetry#54]
Hello!

We recently updated to v1.2.0 and found that our virtualenvs were being put in the wrong place; instead of `~/.cache/virtualenvs` they were being put into `<project-dir>/~/.cache/virtualenvs`.

Our action looked like this:

```
      - name: Install and configure poetry
        uses: snok/install-poetry@v1.2.0
        with:
          virtualenvs-in-project: false
          virtualenvs-path: ~/.cache/virtualenvs
```

I did a bit of investigation and I think this is due to the github input being directly quoted: https://github.com/snok/install-poetry/blob/main/action.yml#L62, whereas previously it was not quoted before being passed to the script: https://github.com/snok/install-poetry/blob/v1.1.8/action.yml#L40, which allowed the shell to expand it.

I can of course hardcode the home directory instead of using `~` but this seems like a common case, so would it be worth changing this to allow expansion again?
