### ISSUE TITLE
poetry config unaffected by action inputs

### ISSUE THREAD

**Issue by willfrey** [snok/install-poetry#55]
I'm a novice with GitHub Actions, so let me preface this by saying that this issue could be entirely on my end :)

Anyways, I'm seeing that `virtualenvs.in-project` is always set to `true` when I run `poetry config --list` as a run action despite the default value for the action input `virtualenvs-in-project` being `false`. I've also noticed that setting the non-local config in a subsequent action, as per the README, does not actually affect the poetry config. Setting subsequent configs with `--local` is visible.

I did notice that the `version` action input is respected because I tested setting this to `latest`, `1.1.10` and `1.1.9` to check if it would respect that and it did.

Am I doing something wrong here? Taking a stab but perhaps the system-wide poetry config file is not writable?

Thanks!

**Comment by sondrelg** [comment]
Thanks for reporting this @willfrey 👏 

We might be loading in some of the inputs incorrectly. I only ever install venvs in-project, since they're simpler to cache, so I've never actually tried setting it to `false`, and I don't think we have a test for it. 

This might be related to the new quoting of inputs mentioned in #54.

Wrt. setting config options in subsequent steps - it's entirely possible that I've made a wrongful assumption at one point. If I understand you correctly, and using `--local` makes this work, maybe we should just update the README 🙂 

Would you be interested in submitting a PR for either of these issues?

If not, I'll probably have time to review this over the weekend at some point.

**Comment by willfrey** [comment]
I can fiddle around with it and if I figure it out, I can submit a PR. But if you have time over the weekend, please don't wait for me 🙂

FWIW, the default settings are fine for me and I agree that having the virtualenv inside of the project is easier for caching.

I was just seeing how the inputs would affect the VENV environment variable as a means of understanding GitHub Actions syntax better.

Quick question just for personal clarity: is the content of the scripts directly unused now? It seems like everything is taking place in action.yml.

**Comment by sondrelg** [comment]
Yeah no worries, happy someone's experimenting, because I'd never have found out about this myself 😛

The scripts folder is legacy. Made some sub-optimal choices design-wise in v1.0 and v1.1. Those versions curl the config script from this repo's main branch, so removing them will break the action for anyone running those versions 😵‍💫

**Comment by willfrey** [comment]
I won't be able to submit a PR to fix this issue (since I'm not making much progress 😓) but I will open another PR that fixes a few minor things like updating  `LATEST_POETRY` to be 1.1.10 and fixing some cosmetic whitespace.

**Comment by sondrelg** [comment]
#57 seems to fix the issue with config arguments not being set correctly.

In regards to setting config options in subsequent steps, I tried replicating the issue in https://github.com/snok/install-poetry/runs/3771474449?check_suite_focus=true, but was unable to do so. Do you have a sample of what your action looked like when you saw the issue @willfrey? 🙂

**Comment by willfrey** [comment]
Let me copy that snippet into my little sandbox repository and try it out to see what's going on before I send you on a fool's errand :)

**Comment by sondrelg** [comment]
Much appreciated 👏

**Comment by willfrey** [comment]
https://github.com/willfrey/learn-github-actions/runs/3772228198?check_suite_focus=true

Check this guy out. `virtualenvs.in-project` seems to fail to be set.

**Comment by sondrelg** [comment]
Huh, yeah that's odd. Might take another look tomorrow 🙂

**Comment by sondrelg** [comment]
So I tried replicating it once again in https://github.com/snok/install-poetry/runs/3775961027?check_suite_focus=true.

Your workflow is 

```yaml
  test-poetry-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: snok/install-poetry@v1.2
      - run: poetry config virtualenvs.in-project false
      - run: poetry config --list
      - run: poetry config virtualenvs.in-project true
      - run: poetry config --list
```

and I set up this:

```yaml
  test-setting-virtualenvs-in-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: poetry config virtualenvs.in-project
      - run: |
          source .github/scripts/assert.sh
          poetry config virtualenvs.in-project true
          assert_in "true" "$(poetry config virtualenvs.in-project)"
      - run: |
          source .github/scripts/assert.sh
          poetry config virtualenvs.in-project false
          assert_in "false" "$(poetry config virtualenvs.in-project)"
      - run: |
          source .github/scripts/assert.sh
          poetry config virtualenvs.in-project true
          assert_in "true" "$(poetry config virtualenvs.in-project)"
```

As far as I can tell, they both use the same action version, and they both try to change the same config setting in the same way, with the same syntax; yet, yours failed and mine worked 🤔

To be certain there's nothing weird about this repo (I think debug-mode is turned on for action runs, so thought that might somehow have something to do with it) I did a test in another repo, and that worked too: https://github.com/snok/pep585-upgrade/runs/3775986917?check_suite_focus=true

So not sure what's going on here exactly - do you have any ideas?
