### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by NixBiks** [snok/install-poetry#64]
Hi @sondrelg 

This looks very neat - I like it! Nice, simple and flexible API you provide.

One question; do you know if this can be tweaked for a monorepo with multiple python applications?

**Comment by mr-bjerre** [comment]
I guess a simple approach could be something like this (note all `project-1`)

```yaml
name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: project-1/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
        working-directory: project-1
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: poetry install --no-interaction
        working-directory: project-1
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/
          coverage report
        working-directory: project-1
```

But this would require us to hardcode every python app and repeat those steps.

**Comment by sondrelg** [comment]
Yeah I don't see any issues with this. You'll always need to either have some dynamic inference of your project structure or hardcode it - I think just hardcoding it will be easier to maintain most of the time.

With respect to your second caveat about installing Poetry several times; this doesn't have to be true actually 🎉 If you add a cache-step just before you `install-poetry` step we can actually cache the whole installation:

```yaml
      - name: Load cached Poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local  # the path depends on the OS
          key: poetry-0  # increment to reset cache
```

See [this](https://github.com/snok/install-poetry#caching-the-poetry-installation) section of the readme for slightly more context 👍 

What exactly would your aim be? To run all tests for all sub-apps every time?
