### ISSUE TITLE
Not working with pyhon 3.10?

### ISSUE THREAD

**Issue by pranasziaukas** [snok/install-poetry#65]
I'd like to run tests with a Poetry environment and python 3.10.
My `pyproject.toml` also enforces this python version
```
python = ">=3.10,<3.11"
```

I grabbed the example from the README (with very minor modifications) and expected it to work:
```yml
name: tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      - name: Install library
        run: poetry install --no-interaction
      - name: Print info
        run: |
          python --version
          poetry env info
          poetry run python --version
      - name: Run tests
        run: make test
```

The "Print info" step is there just for troubleshooting. It returns:
```
python --version
Python 3.10.1

poetry env info
Python:         3.9.9
Implementation: CPython
Path:           /home/runner/work/advent-of-code-2021/advent-of-code-2021/.venv
Valid:          True
System
Platform: linux
OS:       posix
Python:   /opt/hostedtoolcache/Python/3.9.9/x64

poetry run python --version
Python 3.9.9
```

Even though there is python 3.10.1 up and running, it is clearly not picked up by Poetry.

Any recommendations would be appreciated.
