### ISSUE TITLE
Caching doesn't work

### ISSUE THREAD

**Issue by maitham** [snok/install-poetry#73]
Using the recommended settings caching does not work, it seems like things are cached correctly but calling source .venv/bin/activate results in a file not found error

```
on:
  push:
    branches-ignore:
      - main
name: Tests
jobs:
  test-round-pull:
    name: ground Pull
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ground-pull
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "11"
          postgresql db: test-db
          postgresql user: postgres
          postgresql password: local_password
      - name: Check Postgres running
        run: |
          sleep 2
      - name: Check running containers
        run: docker ps -a
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.10
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run tests
        run: |
          source .venv/bin/activate
          poetry run make check-format
          poetry run make mypy
          poetry run make lint
          poetry run make test
```

**Comment by maitham** [comment]
Unfortunately not :( 
<img width="945" alt="image" src="https://user-images.githubusercontent.com/15156137/154360454-5c0629c0-824d-4c9c-9187-0774cf55a878.png">

**Comment by maitham** [comment]
Whats strange is running the following step, before `source .venv/bin/activate` works. But this just installs the dependencies again, which we're trying to avoid.

```
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: poetry install --no-interaction
```

**Comment by sondrelg** [comment]
If you have the opportunity to create a demo project or some reproducible example that would help me a lot. Otherwise, maybe it would be helpful to sprinkle in a few `ls` statements to get a sense of where the venv is located relative to your working directory.

**Comment by miigotu** [comment]
You should restore your cache before installing poetry

**Comment by maitham** [comment]
@sondrelg This still does not fix it!

**Comment by maitham** [comment]
```
on:
  push:
    branches-ignore:
      - main
name: Local Tests - Vital Background Pull
jobs:
  test-vital-background-pull:
    name: Local Tests - Vital Background Pull
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: vital-background-pull
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "11"
          postgresql db: vital-test-db
          postgresql user: postgres
          postgresql password: local_password
      - name: Check running containers
        run: docker ps -a
      - name: Restore pip cache
        uses: actions/cache@v3
        with:
          path: $(python -m pip cache dir)
          key: ubuntu-latest-pip-3.9-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ubuntu-latest-pip-3.9-
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.10
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: false
      - name: Restore poetry cache
        uses: actions/cache@v3
        with:
          path: $(poetry config cache-dir)
          key: ubuntu-latest-poetry-3.9-${{ hashFiles('**/pyproject.toml') }}
      - name: Restore virtualenv
        uses: actions/cache@v3
        id: cache-venv
        with:
          path: .venv
          key: ubuntu-latest-virtualenv-3.9-${{ hashFiles('**/pyproject.toml') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run tests
        run: |
          source .venv/bin/activate
          make check-format
          make mypy
          make lint
          make test
```
