### ISSUE TITLE
Correct virtualenvs-path for caching

### ISSUE THREAD

**Issue by Anselmoo** [snok/install-poetry#81]
I am wondering if  `virtualenvs-path: .venv` is missing? Following the example, only by setting `.venv` allows using the cache. 

_So it actually looks like:_

```yaml
- name: Install Poetry 
         uses: snok/install-poetry@v1 
         with: 
           virtualenvs-create: true 
           virtualenvs-in-project: true 
           installer-parallel: true
           virtualenvs-path: .venv
```
https://github.com/snok/install-poetry/blob/2d5fc9c6ebc5598ab457df508f02aacae318ae92/README.md?plain=1#L111-L126
