### ISSUE TITLE
Issues with cached poetry installation: bad interpreter, no such file

### ISSUE THREAD

**Issue by connortann** [snok/install-poetry#82]
Hi,

I've followed the instructions in the README for caching the poetry installation. It has been working well for several weeks, but recently has started failing with an error "bad interpreter: no such file or directory".

### Our CI steps

https://github.com/bp/resqpy/blob/49f99ad3f135fde650cdd1959a9fdc1c6cbd3424/.github/actions/prepare-poetry/action.yml#L14-L30

```yml
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Load cached Poetry installation
      uses: actions/cache@v2
      with:
        path: ~/.local  # the path depends on the OS
        key: poetry-0  # increment to reset cache

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

```

### Example failed job:

 ([Link to example job](https://github.com/bp/resqpy/runs/6304882816?check_suite_focus=true)):

<details>

Prepare all required actions
Getting action download info
Download action repository 'actions/setup-python@v2' (SHA:7f80679172b057fc5e90d70d197929d454754a5a)
Download action repository 'actions/cache@v2' (SHA:937d24475381cd9c75ae6db12cb4e79714b926ed)
Download action repository 'snok/install-poetry@v1' (SHA:2bf112a0f6979928eb6b011f39700db589c5961e)
Run ./.github/actions/prepare-poetry
Run actions/setup-python@v2
Successfully setup CPython (3.9.12)
Run actions/cache@v2
Received 23265524 of 23265524 (100.0%), 87.4 MBs/sec
Cache Size: ~22 MB (23265524 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/70290b69-13[85](https://github.com/bp/resqpy/runs/6304882816?check_suite_focus=true#step:3:85)-[49](https://github.com/bp/resqpy/runs/6304882816?check_suite_focus=true#step:3:49)18-8afa-e181eef33b05/cache.tzst -P -C /home/runner/work/resqpy/resqpy
Cache restored successfully

Cache restored from key: poetry-0
Run snok/install-poetry@v1
Run $GITHUB_ACTION_PATH/main.sh

Setting Poetry installation path as /home/runner/.local/

Installing Poetry 👷

Retrieving Poetry metadata

The latest version (1.1.13) is already installed.
/home/runner/work/_actions/snok/install-poetry/v1/main.sh: /home/runner/.local//bin/poetry: /home/runner/.local/venv/bin/python: bad interpreter: No such file or directory
/home/runner/work/_actions/snok/install-poetry/v1/main.sh: /home/runner/.local//bin/poetry: /home/runner/.local/venv/bin/python: bad interpreter: No such file or directory
/home/runner/work/_actions/snok/install-poetry/v1/main.sh: /home/runner/.local//bin/poetry: /home/runner/.local/venv/bin/python: bad interpreter: No such file or directory
/home/runner/work/_actions/snok/install-poetry/v1/main.sh: /home/runner/.local//bin/poetry: /home/runner/.local/venv/bin/python: bad interpreter: No such file or directory

Installation completed. Configuring settings 🛠

Done ✅

</details>

The CI job fails with "bad interpreter: no such file or directory.

### Workaround

I found that incrementing the cache key resolves the issue. However, thought I'd share here in case there is a root cause that can be diagnosed & fixed in case others have the same issue
