### ISSUE TITLE
PyTest not recognized in Github Action Workflow with poetry 1.2.0b3

### ISSUE THREAD

**Issue by PhilippWillms** [snok/install-poetry#86]
Hello,

I upgraded my local dev environment from peotry 1.1.14 to poetry 1.2.0b3, as this version contains many bugfixes and useful enhancements. Accodingly, I adjusted the .yml configuration in my private GitHub repo for the CI-CD pipeline.

While the poetry installation works fine, there is an issue with pytest. See the details below.

What I changed is simply the `with version:` part of the `snok/install-poetry@v1` part.

**PyTest error log**

> Run poetry run pytest tests/ --cov=wksim --cov-report=xml
>   **poetry run pytest tests/ --cov=wksim --cov-report=xml**
>   shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
>   env:
>     pythonLocation: C:\hostedtoolcache\windows\Python\3.8.10\x64
>     VENV: .venv/scripts/activate
> 'pytest' is not recognized as an internal or external command,
> operable program or batch file.
> Error: Process completed with exit code 1.

**YAML config**
```
jobs:
  ci:
    # Set up operating system
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    # Define job steps
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Run pre-commit hooks
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit install
        pre-commit run --all-files

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.2.0b3

    - name: Install package
      run: poetry install

    - name: Test with pytest
      run: poetry run pytest tests/ --cov=wksim --cov-report=xml
```

**Comment by sondrelg** [comment]
Could you replace the last line with this and report back?
```yaml
run: |
    source $VENV
    pytest --version  # just to verify it's installed
    pytest tests/ --cov=wksim --cov-report=xml 
```

**Comment by miigotu** [comment]
Might be better if you always want to use bleeding edge to set the INSTALLATION_ARGUMENTS environment variable. 

```yaml
- name: Install Poetry 
  uses:
      snok/install-poetry@v1
      with:
           poetry-version: latest
      env:
          INSTALLATION_ARGUMENTS: "--pre"
```

**Comment by miigotu** [comment]
Might be better if you always want to use bleeding edge to set the INSTALLATION_ARGUMENTS environment variable. 

```yaml
- name: Install Poetry 
  uses:
      snok/install-poetry@v1
      with:
           poetry-version: latest
      env:
          INSTALLATION_ARGUMENTS: "--pre"
```

Also, you don't need to use poetry run, the environment is already activated.
```yaml
- name: Test with pytest
  run: pytest tests/ --cov=wksim --cov-report=xml
```

**Comment by PhilippWillms** [comment]
The bleeding edge parameter is a good idea, but slo bears the risk of unwanted side-effects in future releases. Therefore thanks for the hint, but not implemented now.

After a lot of debugging (unfortunately in live syystem, not with act.exe as this did not work out properly), the configuration below was successful. At the end of the day, it was the property setting `virtualenvs-in-project: false` which fixed the issue initially reported. With activation of virtualenv creation in project, the .yml workflow runner could not determine correctly the virtualenv in the subsequent steps.

```
name: ci

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
  SUPPORTED_PYTHON_VERSIONS: '\"python-version\":[\"3.8\", \"3.9\"]'
  SUPPORTED_OPERATING_SYSTEMS: '\"os\":[\"ubuntu-latest\", \"macos-latest\", \"windows-latest\"]'

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      py-os-matrix: ${{ steps.set-matrix-vars.outputs.py-os-matrix }}
      os-matrix: ${{ steps.set-matrix-vars.outputs.os-matrix }}
    steps:
      - id: set-matrix-vars
        run: |
          echo "::set-output name=py-os-matrix::{${{ env.SUPPORTED_PYTHON_VERSIONS }},${{ env.SUPPORTED_OPERATING_SYSTEMS }}}"
          echo "::set-output name=os-matrix::{${{ env.SUPPORTED_OPERATING_SYSTEMS }}}"

  test-run:
    name: test on ${{ matrix.os }} - ${{ matrix.python-version }}
    needs: set-env
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.set-env.outputs.py-os-matrix) }}
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry in virtual environment
        uses: snok/install-poetry@v1
        with:
          version: 1.2.0b3
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true
      - name: Install library with dependencies
        run: |
          poetry install --with test --no-interaction
      - name: Run pytest suite and create coverage report
        run: |
          poetry run pytest tests/ --cov=wksim --cov-report=xml
```
