### ISSUE TITLE
Error on windows

### ISSUE THREAD

**Issue by NicklasTegner** [snok/install-poetry#9]
Hi.
I am running a workflow, that runs on Mac and Windows.
Mac works perfectly fine.
But on Windows I get the following error:

> D:\a\_temp\ba90638b-3217-4c14-b352-615ff786d16c.sh: line 5: /c/Users/runneradmin/.poetry/env: No such file or directory
Error: Process completed with exit code 1.

**Comment by sondrelg** [comment]
Hi @NicklasTegner, thanks for submitting the issue. 

I'm going to take a look at this tonight and get back to you 👍

**Comment by NicklasTegner** [comment]
hi @sondrelg 

Just to add, here's my configuration (that triggered the error)


    - name: Install Poetry
      uses: snok/install-poetry@v1.0.0
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv

**Comment by sondrelg** [comment]
Thanks! Figured out how to make it run on Windows - just trying to clean up the implementation now and then I'll release a new version shortly 🚀

**Comment by NicklasTegner** [comment]
nice!
Do let me know when the new version is out 👍

**Comment by sondrelg** [comment]
Hey @NicklasTegner,

Just released `v1.1.0`, and Windows should now work. 

Make sure to use:

```yaml
- name: Install Poetry
  uses: snok/install-poetry@v1.1.0
  with:
    virtualenvs-create: true
    virtualenvs-in-project: true
```

(the path setting you've used is not necessary since the default `in-project` path should be .venv)

and then you will need to set the default shell like this, at the job level:

```yaml
defaults:
  run:
    shell: bash
```

I've added a section dedicated to running this action in windows in the updated readme, [here](https://github.com/snok/install-poetry#running-on-windows) that might also be helpful.

If anything is unclear, or it still doesn't work, let me know :)

**Comment by NicklasTegner** [comment]
hi @sondrelg 

I just tried with the updated version, and I get the following now:

```
Poetry (1.1.4) is installed now. Great!

To get started you need Poetry's bin directory (%USERPROFILE%\.poetry\bin) in your `PATH`
environment variable. Future applications will automatically have the
correct environment, but you may need to restart your current shell.

chmod: cannot access 'D:a_actionssnokinstall-poetryv1.1.0/main.sh': No such file or directory
Error: Process completed with exit code 1.
```

And my config is as follows:

Globally:
```
defaults:
  run:
    shell: bash
```
 
And in my Windows job:

```
    - name: Install Poetry
      uses: snok/install-poetry@v1.1.0
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
```

**Comment by sondrelg** [comment]
Yes I see you're right. Must have changed something last minute, because my tests were passing and now they're not 🤔 

I'll take another look at it today after work and get back to you! Thanks for the feedback.

**Comment by sondrelg** [comment]
When you get the opportunity, could you try using `snok/install-poetry@v1.1.1rcN`?

Version `1.1.1rcN` is the pre-release for what I believe fixes the issue.

The issue seems to have been that the built-in Github Actions variable `${{ github.action_path }}` doesn't work correctly on Windows. I had made a pre-release yesterday and tested remotely on `ubuntu-latest` runners, and I had also tested on `windows-latest` runner locally in this action repo; but I had of course forgotten to test windows runners remotely. Sorry about that, hopefully this works (fingers crossed).

**Comment by NicklasTegner** [comment]
Hi.
I see that v1.1.1rcN is here on the page, but my workflow seems unable to find download information for it:

`Failed` to resolve action download info. Error: Unable to resolve action `snok/install-poetry@vv1.1.1rcN`, unable to find version `vv1.1.1rcN`

**Comment by sondrelg** [comment]
I think you might have included one "v" too many. Try `snok/install-poetry@v1.1.1rcN` :)

**Comment by NicklasTegner** [comment]
It's working now, but my problem is, that my Windows job now fails at the end, at the "Complete job" step.
No output, but on the overview I get

```
github-actions/` Windows Builder
.github#L1
Process completed with exit code 1.
```

This error came, after I set the shell to be bash. Any suggestions?
PS: Also still need to verify that caching work, will do that while I try to fix the above error.

**Comment by sondrelg** [comment]
Is your workflow closed source? It might be easier to help if you could link me the full code. 

If it is, perhaps this example can help you: https://github.com/snok/django-swagger-tester/blob/upgrade-action/.github/workflows/testing.yml

This is the branch of another repository that I've used to test an ubuntu/windows matrix on the current pre-release.

**Comment by NicklasTegner** [comment]
yes, the repository is closed, but if you want you are welcome to take a look at my workflow configuration here: https://gist.github.com/06a177cdeaa2946be83077c2f0f4352b

**Comment by sondrelg** [comment]
Sorry for the late response, but my best bet is that one of your other commands will need to be adapted to the shell type. I've finally been able to test this properly, and I thought I would share the workflow I've run.

```yaml
name: test

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3"
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - run: python -m pip install black flake8 isort
      - run: |
          flake8 .
          black . --check
          isort .
  test:
    needs: linting
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.6", "3.7", "3.8", "3.9"]
        django-version: [ "2.2", "3.0", "3.1" ]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: echo "${{ runner.os }}"
      - name: Install poetry
        uses: snok/install-poetry@v1.1.1rcN
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-1
      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: Install django ${{ matrix.django-version }}
        run: |
          source $VENV
          pip install "Django==${{ matrix.django-version }}"
      - name: Install DRF 3.11 on Django 2.2
        if: matrix.django-version == '2.2'
        run: |
          source $VENV
          poetry add "djangorestframework==3.11.1"
      - name: Run tests
        run: |
          poetry run pytest --cov=django_swagger_tester --verbose --assert=plain
          poetry run coverage report
```

and [here](https://github.com/snok/django-swagger-tester/actions/runs/358646431) is a link to the workflow run in case it could be helpful.

I believe with the changes made in `v1.1.1` the poetry install should be stable, but I'm still a little stumped as to why it doesn't work on other shells than bash. Feel free to test further and make commit a PR if you want.
