### ISSUE TITLE
Make the action work on all Windows shells

### ISSUE THREAD

**Issue by sondrelg** [snok/install-poetry#99]
There should be a simple way to run an os-matrix, including windows, regardless of the shell you're running. We can detect which shell is running and adapt accordingly. 

When we say "all" shells, I guess we actually only care about 

- powershell
- bash
- cmd

And cmd might not be that important if we can't easily fix it, but powershell is the default and bash is what we've recommended in the past.

**Comment by cortadocodes** [comment]
I've had to revert to [`v1.3.2`](https://github.com/snok/install-poetry/releases/tag/v1.3.2) of this action to get it working again with Windows.

**Comment by sondrelg** [comment]
What does your workflow looks like? That's unfortunate.

**Comment by cortadocodes** [comment]
https://github.com/octue/octue-sdk-python/blob/feature/add-topic-and-subscription-creation-command/.github/workflows/python-ci.yml

**Comment by sondrelg** [comment]
Can't see that there's anything wrong with the action. Your workflow should work on the latest if you set the shell to bash, as described [here](https://github.com/snok/install-poetry#running-on-windows) I think

[These](https://github.com/snok/install-poetry/actions/runs/3242757736/workflow) are the tests we're running, and everything seems good. If the action was broken for windows I think we'd see it, no? Can you see anything missing?

**Comment by cortadocodes** [comment]
I tried setting the shell to bash as recommended:
- It fixed the `poetry check` step (`poetry` wasn't found as a commandlet before)
- But the tests in the `tox` step failed

Here are the workflow runs showing the failures - hope they help!
- [Using the latest version of `snok/install-poetry`](https://github.com/octue/octue-sdk-python/actions/runs/3241777438/jobs/5314170866#step:5:17)
- [Using the latest version of `snok/install-poetry` with the default shell set to `bash`](https://github.com/octue/octue-sdk-python/actions/runs/3241915428/jobs/5314490556#step:8:212)

**Comment by miigotu** [comment]
You have to install poetry into the tox environment. However, and this might be a silly question, why are you using tox to run the tests when you are using GitHub actions and poetry? `poetry run pytest` or unittest or whatever is already going to run your tests in a python virtual envelope, and you can separate environments with a GitHub actions matrix.

**Comment by cortadocodes** [comment]
I can do that if necessary but I didn't have to for any of the previous versions of `snok/install-poetry`. This is what's making me think there's a bug or a breaking change somewhere in the latest version.

We're still using `tox` because it allows us to test in other environments than a GHA worker if we need to and gives us more control than just using GHA. We are using a GHA OS matrix for MacOS, Linux, and Windows. The `install-poetry` action is only failing on the Windows runner.

**Comment by miigotu** [comment]
> I can do that if necessary but I didn't have to for any of the previous versions of `snok/install-poetry`. This is what's making me think there's a bug or a breaking change somewhere in the latest version.
> 
> We're still using `tox` because it allows us to test in other environments than a GHA worker if we need to and it gives us more control than just using GHA. We are using a GHA OS matrix for MacOS, Linux, and Windows. The `install-poetry` action is only failing on the Windows runner.
> 
> 

There for sure is something broken right now. I just figured tox-poetry would be useful. If tox is configured to use an existing environment it could be a problem here, but if tox is creating the environment and then can't find poetry that's because tox is properly sandboxing the environment. Any tools you use inside the toxenv need to be installed by tox itself.

**Comment by cortadocodes** [comment]
Ah I see, thank you! We're using tox with poetry whitelisted

**Comment by Hasenpfote** [comment]
@cortadocodes 
When using `allowlist_externals`, `Tox` needs a path to find `Poetry`.

This is one example that works for me.

`tox.ini`
```ini
[tox]
envlist =
    py{37,38}
skipsdist = true
isolated_build = true

[testenv]
allowlist_externals =
    poetry
commands_pre =
    poetry install --with test -v
commands =
    poetry run pytest --cov --cov-append --cov-report=term-missing -v
...
```

`.github/workflows/debug3.yml`
```yaml
name: Caching Poetry on Windows

on: workflow_dispatch

permissions:
  contents: read

jobs:
  create-cache:
    name: caching 1/2 - ${{ matrix.os }}, ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ['3.7', ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: | 
              ~\.local\VERSION
              #~\.local\bin\poetry.exe
              ~\.local\venv
          key: temp-3-poetry-${{ matrix.os }}-python-${{ matrix.python-version }}

      - name: Install Poetry for Windows
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1

      - name: Add Poetry to the PATH environment variable
        shell: bash
        run: |
          #echo "${USERPROFILE}\.local\bin" >> $GITHUB_PATH
          echo "${USERPROFILE}\.local\venv\Scripts" >> $GITHUB_PATH
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: temp-3-venv-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root --with dev

      - name: Install project
        run: poetry install --no-interaction --only-root

      - name: Debug
        shell: cmd
        run: |
          set PATH

      - name: Test with pytest
        shell: bash
        run: |
          if [ $RUNNER_OS == 'Windows' ]; then
            # Avoid referencing the wrong Python version.
            VER='${{ matrix.python-version }}'
            ARR=(${VER//./ })
            poetry run tox -e "py${ARR[0]}${ARR[1]}"
          else
            poetry run tox -e py
          fi

  # Same as above.
  load-cache:
    needs: create-cache
    name: caching 2/2 - ${{ matrix.os }}, ${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ['3.7', ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: | 
              ~\.local\VERSION
              #~\.local\bin\poetry.exe
              ~\.local\venv
          key: temp-3-poetry-${{ matrix.os }}-python-${{ matrix.python-version }}

      - name: Install Poetry for Windows
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1

      - name: Add Poetry to the PATH environment variable
        shell: bash
        run: |
          #echo "${USERPROFILE}\.local\bin" >> $GITHUB_PATH
          echo "${USERPROFILE}\.local\venv\Scripts" >> $GITHUB_PATH

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: temp-3-venv-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root --with dev

      - name: Install project
        run: poetry install --no-interaction --only-root

      - name: Debug
        shell: cmd
        run: |
          set PATH

      - name: Test with pytest
        shell: bash
        run: |
          if [ $RUNNER_OS == 'Windows' ]; then
            # Avoid referencing the wrong Python version.
            VER='${{ matrix.python-version }}'
            ARR=(${VER//./ })
            poetry run tox -e "py${ARR[0]}${ARR[1]}"
          else
            poetry run tox -e py
          fi
```

Tox will fail if the path to Poetry is assigned in POSIX style.  

This is an example that works, but it is partially mixed.  
![2022-12-27 09 55 05 github com 3e074d89835f](https://user-images.githubusercontent.com/1502467/209594227-476052d3-de39-40c5-ab81-9e6ddaa55aef.png)

Please use Tox3 for verification.
Tox4 doesn't ensure.

This log may disappear after a while.
[log](https://github.com/Hasenpfote/github_actions_testing3/actions/runs/3784215088/jobs/6433340288)
